# Ramyasahithya Magani - G01425752
# Arsitha Sathu - G01445215
# Athiksha Venkannagari - G01461169
# Sreshta Kosaraju - G01460468

# Kubernetes deployment.yaml file defines a replica set of three instances for student survey application,
# using the specified Docker image and exposing port 80.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-survey-deployment
  labels:
    app: surveydata
spec:
  replicas: 3
  selector:
    matchLabels:
      app: surveydata
  template:
    metadata:
      labels:
        app: surveydata
    spec:
      containers:
        - name: surveydata-container
          image: ramya0602/spring_surveyform:${IMAGE_TAG}
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: dockerkey
