apiVersion: v1
kind: Service
metadata:
  name: surveydata-service
  labels:
    run: surveydata
spec:
  selector:
    app: surveydata
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
    - port: 443
      protocol: TCP
      name: https
